- name: VIAVI Test Automation
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:

    - name: Iterrate campagines and include task
      loop: "{{ tma_campaigns }}"
      ansible.builtin.include_tasks:
        file: tasks/run_campaign.yaml
      loop_control:
        loop_var: tma_campaign
